import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="text-slate-900 bg-slate-100 min-h-screen">
          <div className="max-w-5xl mx-auto px-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
