import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/Header";
import { ToastContainer } from "react-toastify";
import { Footer } from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="min-h-screen scroll-smooth md:scroll-auto">
      <Header />
      <body>{children}</body>
      <Footer />
      <ToastContainer />
    </html>
  );
}
